### ISSUE TITLE
Arregla classifiers en mongo

### ISSUE THREAD

**Issue by llazzaro** [flaskpackages/flaskpackages#11]

**Comment by DobleV55** [comment]
mongoengine.errors.FieldDoesNotExist: The fields "{'Framework', 'License', 'Development Status', 'Programming Language'}" do not exist on the document "Classifier" 
FROM 'Framework', 'License', 'Development Status', 'Programming Language' > 'framework','license','development_status','programming_language'

**Comment by llazzaro** [comment]
https://github.com/flaskpackages/flaskpackages/commit/29f16cf14afdb0c642a537e794574638f7856a19
